# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mhmf6CIq6JI4ZmFhXO9F33NmyxZHx2LV
"""

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>R.R SERVIÇOS - Serviços</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>

  <h1>Serviços para Construção Civil</h1>

  <div class="servico">
    <h2>Monitoramento de Frota</h2>
    <img src="imagens/monitoramento.jpg" alt="Monitoramento de Frota">
    <p>Descrição do serviço de monitoramento de frota...</p>
  </div>

  <div class="servico">
    <h2>Venda de Materiais</h2>
    <img src="imagens/materiais.jpg" alt="Venda de Materiais">
    <p>Descrição do serviço de venda de materiais...</p>
  </div>

</body>
</html>
"""

display(HTML(html_code))

# This appears to be HTML code, not Python.
# If you want to generate HTML content from Python, you can do it like this:

html_content = """<!DOCTYPE html>
<html>
<head>
</head>
</html>"""

print(html_content)
  <title>R.R SERVIÇOS - Serviços</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>

  <header>
    <h1>R.R SERVIÇOS</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Sobre Nós</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Monitoramento de Frota</h2>
      <img src="imagens/monitoramento.jpg" alt="Monitoramento de Frota">
      <p>Tenha controle total da sua frota com nosso sistema de monitoramento em tempo real. Otimize rotas, reduza custos e aumente a segurança dos seus veículos.</p>
      <ul>
        <li>Rastreamento GPS preciso</li>
        <li>Relatórios detalhados de desempenho</li>
        <li>Alertas de segurança em tempo real</li>
        <li>Equipe especializada para suporte</li>
      </ul>
      <button>Solicitar Orçamento</button>
    </section>

    <section class="servico">
      <h2>Venda de Materiais</h2>
      <img src="imagens/materiais.jpg" alt="Venda de Materiais">
   do o que você precisa para sua obra em um só lugar. Oferecemos uma ampla variedade de materiais de construção de alta qualidade, com preços competitivos e entrega rápida.</p>
      <ul>
        <li>Cimento, areia, tijolos e muito mais</li>
        <li>Grandes marcas e fornecedores confiáveis</li>
        <li>Estoque completo para pronta entrega</li>
        <li>Condições de pagamento facilitadas</li>
      </ul>
      <button>Ver Catálogo</button>
    </section>

    <section class="depoimentos">
      <h2>Depoimentos de Clientes</h2>
      <div class="depoimento">
        <p>"A R.R SERVIÇOS nos ajudou a reduzir os custos com combustíveis em 15% com o monitoramento de frota. Recomendo!" - João Silva, Empresa XYZ</p>
      </div>
      <div class="depoimento">
        <p>"Sempre encontro os materiais que preciso na R.R SERVIÇOS, com preços justos e entrega rápida. Ótimo atendimento!" - Maria Souza, Construtora ABC</p>
      </div>
    </section>

    <section class="contato">
      <h2>Entre em Contato</h2>
      <form>
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>

        <label for="mensagem">Mensagem:</label>
        <textarea id="mensagem" name="mensagem" required></textarea>

        <button type="submit">Enviar</button>
      </form>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 R.R SERVIÇOS - <a href="tel:+5511999999999">+55 11 99999-9999</a> - <a href="mailto:contato@rrservicos.com">contato@rrservicos.com</a></p>
    </footer>

</body>
</html>   <p>Encontre tu

# This appears to be HTML code, not Python.
# If you want to generate HTML content from Python, you can do it like this:
from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>R.R SERVIÇOS - Serviços</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  ... (resto do código HTML) ...
</body>
</html>
"""

display(HTML(html_code)) # Esta linha exibe o conteúdo HTML na saída

html_content = """<!DOCTYPE html>
<html>
<head>
</head>
<body>
</body>
</html>"""


print(html_content)
  <title>R.R SERVIÇOS - Serviços</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>

  <header>
    <h1>R.R SERVIÇOS</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Sobre Nós</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Monitoramento de Frota</h2>
      <img src="imagens/monitoramento.jpg" alt="Monitoramento de Frota">
      <p>Tenha controle total da sua frota com nosso sistema de monitoramento em tempo real. Otimize rotas, reduza custos e aumente a segurança dos seus veículos.</p>
      <ul>
        <li>Rastreamento GPS preciso</li>
        <li>Relatórios detalhados de desempenho</li>
        <li>Alertas de segurança em tempo real</li>
        <li>Equipe especializada para suporte</li>
      </ul>
      <button>Solicitar Orçamento</button>
    </section>

    <section class="servico">
      <h2>Venda de Materiais</h2>
      <img src="imagens/materiais.jpg" alt="Venda de Materiais">
      <p>Encontre tudo o que você precisa para sua obra em um só lugar. Oferecemos uma ampla variedade de materiais de construção de alta qualidade, com preços competitivos e entrega rápida.</p>
      <ul>
        <li>Cimento, areia, tijolos e muito mais</li>
        <li>Grandes marcas e fornecedores confiáveis</li>
        <li>Estoque completo para pronta entrega</li>
        <li>Condições de pagamento facilitadas</li>
      </ul>
      <button>Ver Catálogo</button>
    </section>

    <section class="depoimentos">
      <h2>Depoimentos de Clientes</h2>
      <div class="depoimento">
        <p>"A R.R SERVIÇOS nos ajudou a reduzir os custos com combustíveis em 15% com o monitoramento de frota. Recomendo!" - João Silva, Empresa XYZ</p>
      </div>
      <div class="depoimento">
        <p>"Sempre encontro os materiais que preciso na R.R SERVIÇOS, com preços justos e entrega rápida. Ótimo atendimento!" - Maria Souza, Construtora ABC</p>
      </div>
    </section>

    <section class="contato">
      <h2>Entre em Contato</h2>
      <form>
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>

        <label for="mensagem">Mensagem:</label>
        <textarea id="mensagem" name="mensagem" required></textarea>

        <button type="submit">Enviar</button>
      </form>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 R.R SERVIÇOS - <a href="tel:+5511999999999">+55 11 99999-9999</a> - <a href="mailto:contato@rrservicos.com">contato@rrservicos.com</a></p>
    </footer>

</body>
</html>

# prompt: from IPython.display import display, HTML
# html_code = """
# <!DOCTYPE html>
# <html>
# <head>
#   <title>R.R SERVIÇOS - Serviços</title>
#   <link rel="stylesheet" href="style.css">
# </head>
# <body>
#   ... (resto do código HTML) ...
# </body>
# </html>
# """
# display(HTML(html_code))
# html_content = """<!DOCTYPE html>
# <html>
# <head>
#   <title>R.R SERVIÇOS - Serviços</title> <--- Linha corrigida
# </head>
# <body>
# </body

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>R.R SERVIÇOS - Serviços</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <h1>R.R SERVIÇOS</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Sobre Nós</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Monitoramento de Frota</h2>
      <img src="imagens/monitoramento.jpg" alt="Monitoramento de Frota">
      <p>Tenha controle total da sua frota com nosso sistema de monitoramento em tempo real. Otimize rotas, reduza custos e aumente a segurança dos seus veículos.</p>
      <ul>
        <li>Rastreamento GPS preciso</li>
        <li>Relatórios detalhados de desempenho</li>
        <li>Alertas de segurança em tempo real</li>
        <li>Equipe especializada para suporte</li>
      </ul>
      <button>Solicitar Orçamento</button>
    </section>

    <section class="servico">
      <h2>Venda de Materiais</h2>
      <img src="imagens/materiais.jpg" alt="Venda de Materiais">
      <p>Encontre tudo o que você precisa para sua obra em um só lugar. Oferecemos uma ampla variedade de materiais de construção de alta qualidade, com preços competitivos e entrega rápida.</p>
      <ul>
        <li>Cimento, areia, tijolos e muito mais</li>
        <li>Grandes marcas e fornecedores confiáveis</li>
        <li>Estoque completo para pronta entrega</li>
        <li>Condições de pagamento facilitadas</li>
      </ul>
      <button>Ver Catálogo</button>
    </section>

    <section class="depoimentos">
      <h2>Depoimentos de Clientes</h2>
      <div class="depoimento">
        <p>"A R.R SERVIÇOS nos ajudou a reduzir os custos com combustíveis em 15% com o monitoramento de frota. Recomendo!" - João Silva, Empresa XYZ</p>
      </div>
      <div class="depoimento">
        <p>"Sempre encontro os materiais que preciso na R.R SERVIÇOS, com preços justos e entrega rápida. Ótimo atendimento!" - Maria Souza, Construtora ABC</p>
      </div>
    </section>

    <section class="contato">
      <h2>Entre em Contato</h2>
      <form>
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>

        <label for="mensagem">Mensagem:</label>
        <textarea id="mensagem" name="mensagem" required></textarea>

        <button type="submit">Enviar</button>
      </form>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 R.R SERVIÇOS - <a href="tel:+5511999999999">+55 11 99999-9999</a> - <a href="mailto:contato@rrservicos.com">contato@rrservicos.com</a></p>
  </footer>

</body>
</html>
"""

display(HTML(html_code))

# prompt: quero criar um site  de venda de serviços  ligado para cachorro serviços de tosa  de veterinaria e venda de acessorio e medicamento e raçao na pagina tenha imagen de cachorros e gatos e do medico veterinario

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>Pet Care Center - Seu Melhor Amigo em Boas Mãos</title>
  <style>
    body {
      font-family: sans-serif;
    }
    header {
      background-color: #f0f0f0;
      padding: 1em;
      text-align: center;
    }
    nav ul {
      list-style: none;
      padding: 0;
    }
    nav li {
      display: inline;
      margin: 0 1em;
    }
    .servico {
      border: 1px solid #ccc;
      padding: 1em;
      margin: 1em;
      text-align: center;
    }
    .servico img {
      max-width: 200px;
      height: auto;
    }
    footer {
      background-color: #333;
      color: #fff;
      padding: 1em;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Pet Care Center</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Veterinário</a></li>
        <li><a href="#">Loja</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Tosa e Banho</h2>
      <img src="https://via.placeholder.com/200x200?text=Tosa" alt="Tosa e Banho">
      <p>Oferecemos serviços de tosa e banho para cães e gatos de todas as raças e portes. Utilize produtos de alta qualidade e profissionais experientes.</p>
    </section>

    <section class="servico">
      <h2>Veterinário</h2>
      <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário">
      <p>Consultas veterinárias completas com profissionais qualificados para cuidar da saúde do seu pet. Atendimento com carinho e dedicação.</p>
    </section>

    <section class="servico">
      <h2>Loja</h2>
      <img src="https://via.placeholder.com/200x200?text=Loja" alt="Loja">
      <p>Encontre uma variedade de produtos para seu pet, incluindo ração, medicamentos, acessórios e muito mais. Produtos de qualidade e preços competitivos.</p>
    </section>

    <section>
      <h2>Nossos Pets</h2>
      <div style="display: flex; justify-content: space-around;">
        <img src="https://via.placeholder.com/200x200?text=Cachorro" alt="Cachorro" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Gato" alt="Gato" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário" style="width: 200px; height: auto;">
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 Pet Care Center - Seu Melhor Amigo em Boas Mãos</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))



# prompt: quero criar um site  de venda de serviços  ligado para cachorro serviços de tosa  de veterinaria e venda de acessorio e medicamento e raçao na pagina tenha imagen de cachorros e gatos e do medico veterinario

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>Pet Care Center - Seu Melhor Amigo em Boas Mãos</title>
  <style>
    body {
      font-family: sans-serif;
    }
    header {
      background-color: #f0f0f0;
      padding: 1em;
      text-align: center;
    }
    nav ul {
      list-style: none;
      padding: 0;
    }
    nav li {
      display: inline;
      margin: 0 1em;
    }
    .servico {
      border: 1px solid #ccc;
      padding: 1em;
      margin: 1em;
      text-align: center;
    }
    .servico img {
      max-width: 200px;
      height: auto;
    }
    footer {
      background-color: #333;
      color: #fff;
      padding: 1em;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Pet Care Center</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Veterinário</a></li>
        <li><a href="#">Loja</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Tosa e Banho</h2>
      <img src="https://via.placeholder.com/200x200?text=Tosa" alt="Tosa e Banho">
      <p>Oferecemos serviços de tosa e banho para cães e gatos de todas as raças e portes. Utilize produtos de alta qualidade e profissionais experientes.</p>
    </section>

    <section class="servico">
      <h2>Veterinário</h2>
      <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário">
      <p>Consultas veterinárias completas com profissionais qualificados para cuidar da saúde do seu pet. Atendimento com carinho e dedicação.</p>
    </section>

    <section class="servico">
      <h2>Loja</h2>
      <img src="https://via.placeholder.com/200x200?text=Loja" alt="Loja">
      <p>Encontre uma variedade de produtos para seu pet, incluindo ração, medicamentos, acessórios e muito mais. Produtos de qualidade e preços competitivos.</p>
    </section>

    <section>
      <h2>Nossos Pets</h2>
      <div style="display: flex; justify-content: space-around;">
        <img src="https://via.placeholder.com/200x200?text=Cachorro" alt="Cachorro" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Gato" alt="Gato" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário" style="width: 200px; height: auto;">
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 Pet Care Center - Seu Melhor Amigo em Boas Mãos</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))

# prompt: quero criar um site  de venda de serviços  ligado para cachorro serviços de tosa  de veterinaria e venda de acessorio e medicamento e raçao na pagina tenha imagen de cachorros e gatos e do medico veterinario

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>Pet Care Center - Seu Melhor Amigo em Boas Mãos</title>
  <style>
    body {
      font-family: sans-serif;
    }
    header {
      background-color: #f0f0f0;
      padding: 1em;
      text-align: center;
    }
    nav ul {
      list-style: none;
      padding: 0;
    }
    nav li {
      display: inline;
      margin: 0 1em;
    }
    .servico {
      border: 1px solid #ccc;
      padding: 1em;
      margin: 1em;
      text-align: center;
    }
    .servico img {
      max-width: 200px;
      height: auto;
    }
    footer {
      background-color: #333;
      color: #fff;
      padding: 1em;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Pet Care Center</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Veterinário</a></li>
        <li><a href="#">Loja</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Tosa e Banho</h2>
      <img src="https://via.placeholder.com/200x200?text=Tosa" alt="Tosa e Banho">
      <p>Oferecemos serviços de tosa e banho para cães e gatos de todas as raças e portes. Utilize produtos de alta qualidade e profissionais experientes.</p>
    </section>

    <section class="servico">
      <h2>Veterinário</h2>
      <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário">
      <p>Consultas veterinárias completas com profissionais qualificados para cuidar da saúde do seu pet. Atendimento com carinho e dedicação.</p>
    </section>

    <section class="servico">
      <h2>Loja</h2>
      <img src="https://via.placeholder.com/200x200?text=Loja" alt="Loja">
      <p>Encontre uma variedade de produtos para seu pet, incluindo ração, medicamentos, acessórios e muito mais. Produtos de qualidade e preços competitivos.</p>
    </section>

    <section>
      <h2>Nossos Pets</h2>
      <div style="display: flex; justify-content: space-around;">
        <img src="https://via.placeholder.com/200x200?text=Cachorro" alt="Cachorro" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Gato" alt="Gato" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário" style="width: 200px; height: auto;">
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 Pet Care Center - Seu Melhor Amigo em Boas Mãos</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))

ft# prompt: quero criar um site  de venda de serviços  ligado para cachorro serviços de tosa  de veterinaria e venda de acessorio e medicamento e raçao na pagina tenha imagen de cachorros e gatos e do medico veterinario

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>Pet Care Center - Seu Melhor Amigo em Boas Mãos</title>
  <style>
    body {
      font-family: sans-serif;
    }
    header {
      background-color: #f0f0f0;
      padding: 1em;
      text-align: center;
    }
    nav ul {
      list-style: none;
      padding: 0;
    }
    nav li {
      display: inline;
      margin: 0 1em;
    }
    .servico {
      border: 1px solid #ccc;
      padding: 1em;
      margin: 1em;
      text-align: center;
    }
    .servico img {
      max-width: 200px;
      height: auto;
    }
    footer {
      background-color: #333;
      color: #fff;
      padding: 1em;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Pet Care Center</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Veterinário</a></li>
        <li><a href="#">Loja</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Tosa e Banho</h2>
      <img src="https://via.placeholder.com/200x200?text=Tosa" alt="Tosa e Banho">
      <p>Oferecemos serviços de tosa e banho para cães e gatos de todas as raças e portes. Utilize produtos de alta qualidade e profissionais experientes.</p>
    </section>

    <section class="servico">
      <h2>Veterinário</h2>
      <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário">
      <p>Consultas veterinárias completas com profissionais qualificados para cuidar da saúde do seu pet. Atendimento com carinho e dedicação.</p>
    </section>

    <section class="servico">
      <h2>Loja</h2>
      <img src="https://via.placeholder.com/200x200?text=Loja" alt="Loja">
      <p>Encontre uma variedade de produtos para seu pet, incluindo ração, medicamentos, acessórios e muito mais. Produtos de qualidade e preços competitivos.</p>
    </section>

    <section>
      <h2>Nossos Pets</h2>
      <div style="display: flex; justify-content: space-around;">
        <img src="https://via.placeholder.com/200x200?text=Cachorro" alt="Cachorro" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Gato" alt="Gato" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário" style="width: 200px; height: auto;">
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 Pet Care Center - Seu Melhor Amigo em Boas Mãos</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))

# prompt: quero criar um site  de venda de serviços  ligado para cachorro serviços de tosa  de veterinaria e venda de acessorio e medicamento e raçao na pagina tenha imagen de cachorros e gatos e do medico veterinario

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>Pet Care Center - Seu Melhor Amigo em Boas Mãos</title>
  <style>
    body {
      font-family: sans-serif;
    }
    header {
      background-color: #f0f0f0;
      padding: 1em;
      text-align: center;
    }
    nav ul {
      list-style: none;
      padding: 0;
    }
    nav li {
      display: inline;
      margin: 0 1em;
    }
    .servico {
      border: 1px solid #ccc;
      padding: 1em;
      margin: 1em;
      text-align: center;
    }
    .servico img {
      max-width: 200px;
      height: auto;
    }
    footer {
      background-color: #333;
      color: #fff;
      padding: 1em;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Pet Care Center</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Veterinário</a></li>
        <li><a href="#">Loja</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Tosa e Banho</h2>
      <img src="https://via.placeholder.com/200x200?text=Tosa" alt="Tosa e Banho">
      <p>Oferecemos serviços de tosa e banho para cães e gatos de todas as raças e portes. Utilize produtos de alta qualidade e profissionais experientes.</p>
    </section>

    <section class="servico">
      <h2>Veterinário</h2>
      <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário">
      <p>Consultas veterinárias completas com profissionais qualificados para cuidar da saúde do seu pet. Atendimento com carinho e dedicação.</p>
    </section>

    <section class="servico">
      <h2>Loja</h2>
      <img src="https://via.placeholder.com/200x200?text=Loja" alt="Loja">
      <p>Encontre uma variedade de produtos para seu pet, incluindo ração, medicamentos, acessórios e muito mais. Produtos de qualidade e preços competitivos.</p>
    </section>

    <section>
      <h2>Nossos Pets</h2>
      <div style="display: flex; justify-content: space-around;">
        <img src="https://via.placeholder.com/200x200?text=Cachorro" alt="Cachorro" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Gato" alt="Gato" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário" style="width: 200px; height: auto;">
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 Pet Care Center - Seu Melhor Amigo em Boas Mãos</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))

# prompt: quero criar um site  de venda de serviços  ligado para cachorro serviços de tosa  de veterinaria e venda de acessorio e medicamento e raçao na pagina tenha imagen de cachorros e gatos e do medico veterinario

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html>
<head>
  <title>Pet Care Center - Seu Melhor Amigo em Boas Mãos</title>
  <style>
    body {
      font-family: sans-serif;
    }
    header {
      background-color: #f0f0f0;
      padding: 1em;
      text-align: center;
    }
    nav ul {
      list-style: none;
      padding: 0;
    }
    nav li {
      display: inline;
      margin: 0 1em;
    }
    .servico {
      border: 1px solid #ccc;
      padding: 1em;
      margin: 1em;
      text-align: center;
    }
    .servico img {
      max-width: 200px;
      height: auto;
    }
    footer {
      background-color: #333;
      color: #fff;
      padding: 1em;
      text-align: center;
    }
  </style>
</head>
<body>
  <header>
    <h1>Pet Care Center</h1>
    <nav>
      <ul>
        <li><a href="#">Início</a></li>
        <li><a href="#">Serviços</a></li>
        <li><a href="#">Veterinário</a></li>
        <li><a href="#">Loja</a></li>
        <li><a href="#">Contato</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section class="servico">
      <h2>Tosa e Banho</h2>
      <img src="https://via.placeholder.com/200x200?text=Tosa" alt="Tosa e Banho">
      <p>Oferecemos serviços de tosa e banho para cães e gatos de todas as raças e portes. Utilize produtos de alta qualidade e profissionais experientes.</p>
    </section>

    <section class="servico">
      <h2>Veterinário</h2>
      <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário">
      <p>Consultas veterinárias completas com profissionais qualificados para cuidar da saúde do seu pet. Atendimento com carinho e dedicação.</p>
    </section>

    <section class="servico">
      <h2>Loja</h2>
      <img src="https://via.placeholder.com/200x200?text=Loja" alt="Loja">
      <p>Encontre uma variedade de produtos para seu pet, incluindo ração, medicamentos, acessórios e muito mais. Produtos de qualidade e preços competitivos.</p>
    </section>

    <section>
      <h2>Nossos Pets</h2>
      <div style="display: flex; justify-content: space-around;">
        <img src="https://via.placeholder.com/200x200?text=Cachorro" alt="Cachorro" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Gato" alt="Gato" style="width: 200px; height: auto;">
        <img src="https://via.placeholder.com/200x200?text=Veterinário" alt="Veterinário" style="width: 200px; height: auto;">
      </div>
    </section>
  </main>

  <footer>
    <p>&copy; 2023 Pet Care Center - Seu Melhor Amigo em Boas Mãos</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))